version: "3.8"
services:
  web:
      build: ./frontend

      expose:
        - 8000
      # ports:
      #   - 8000:8000
      networks:
        - my-network
  database:
      image: postgres:alpine3.17
      environment:
        - POSTGRES_USER=stoyanov
        - POSTGRES_PASSWORD=tt036122758!
        - POSTGRES_DB=mypostgres
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgres/data  
      networks:
        - my-network

  nginx:
      container_name: nginx
      image: nginx
      build: ./nginx_d_file
      ports:
        - 80:80    
      depends_on:
        - web
      networks:
        - my-network
volumes:
  pgdata:


networks:
  my-network: