name: ci

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "main"
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      -
        name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mydevrepo:${{ env.RELEASE_VERSION }}
