name: ci

on:
  push:
    branches:
      - "main"
      
jobs:
  build:
    env:
        IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mydevrepo
    runs-on: ubuntu-latest
    steps:
      -
       name: Generate build ID
       id: prep
       run: |
          name=${{vars.NAME}}
          sha=${GITHUB_REF}
          echo "::set-output name=BUILD_ID::${name}-${sha}"          
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}  
