name: Deploy to VM
on:
 push:
   branches: [main]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Deploy to VM
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
             cd /home/azureuser/myDevProject
             git stash
             git pull origin main
             sudo docker build -t myapp:last .
             sudo docker run --name my_app -p 5000:5000 -d myapp:last
             
