name: VmHub

on:
  push:
    branches:
      - "main"
      
jobs:
    build:
      name: Build an image
      env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mydevrepo
      runs-on: ubuntu-latest
      steps:
        -
         name: Generate build ID
         id: prep
         run: |
            name=${{vars.NAME}}
            sha=${GITHUB_SHA:0:7}
            echo "::set-output name=BUILD_ID::${name}-${sha}"          
        -
          name: Checkout
          uses: actions/checkout@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Build
          run: |
              commands:
                - docker-compose build
                - docker tag my-devops-project-frontend:latest ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
                - docker push ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}

    pull:
       name: Pull from DockerHub
       env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mydevrepo
       if: ${{ success() }}
       runs-on: ubuntu-latest
       needs: build
       steps:
       -  name: Generate build ID
          id: prep
          run: |
              name=${{vars.NAME}}
              sha=${GITHUB_SHA:0:7}
              echo "::set-output name=BUILD_ID::${name}-${sha}"
       
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
       - name: Deploy to VM
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
                 docker container rm -f $(docker container ls -aq)
                 docker image rm -f $(docker image ls -q)
                 docker pull ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
                 docker-compose up -d
                 

